projects:
  cdk-amicii-appsync-api:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/AmiciiAPI.ts
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: 4qya7awf5rd7bfpbqt2e4m3oiy
        maxDepth: 2
extensions:
  amplify:
    version: 3
